[package]
name = "drken-book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.5"

[[bin]]
name = "1-meiro"
path = "src/1-meiro.rs"
